archive/history2020.md
=> Update past records (2nd & 5th)

archive/history2020.md
=> Add 6th archives

archive/history2020.md
=> Add 7th archives

archive/history2021.md
=> Add 13th archive

archive/history2021.md
=> 第16回のアーカイブを追加いたしましたわ！

archive/history2021.md
=> Add the 15th archive

archive/history2022.md, index.md
=> Add the 20th archive

archive/history2022.md
レビュー担当大臣！！コードレビューは任せましてよ！！！！！！！！
=> Add the 21st archive

archive/harurobosemi2022.md
（デプロイしたら変わるかもしれないけれど）見やすいようにサイズ変えてみました．
=> Change iframe size properties to show a PDF file

archive/history2022.md
=> Add 24th archive

index.md
=> Update an orginizer affiliation

archive/history2022.md
=> Add 26th archive

archive/history2022.md
=> add the 27th archive

archive/history2022.md, index.md
=> Add the archives of robosemi from the 28th to the 31st

archive/history2023.md
=> Create history2023.md and add 34th archive

archive/history2023.md
=> Add the 32nd and 33rd archives

archive/history2023.md
沢山追加しましてよ〜〜〜
いくつか確認中の資料がありまして，後で爺が追加してくれる予定でしてよ！
=> Add 36th,37th,39th,40th,41st archives

archive/history2024.md, index.md
=> Add the 43rd archives

archive/history2023.md
=> 第42回のアーカイブですわ〜〜〜

archive/history2024.md
=> add archives(44,45,46,47)

archive/history2024.md, index.md
=> Add the 48th archive
